### PR TITLE
Museun_2

### PR DESCRIPTION
**Pull request by AndriiYelieva**
[DEMO LINK](https://AndriiYelieva.github.io/Museum_2/).

### CODE REVIEW

**Review by vlad-demchuk — CHANGES_REQUESTED** [review]
1. header should be 100vh
image
it doesn't match the mock up
image

2. make it a link to some anchor as well
also, add hovers and transitions to all clickable elements
image

3. these should be links to corresponding blocks
image
4. checklist
image
5. form fields should be required, form submission should clear fields
image

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
this arrow not working
Screenshot 2023-02-28 at 10 32 35 AM

page shouldn't refresh after email sent

it's looks weird for tablets
Screenshot 2023-02-28 at 10 40 31 AM

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
Good job, but let's improve
- add hover effect to these buttons
image

- make all hover effects smooth in both directions(don't set `transition ` under `:hover`)
- remove the background on auto-completing
image

- also add hover effect
image

- something went wrong
image

- fix the images in this section on mobile
image

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. fix this bug
image
2. menu also need to has 100vh 
3. 
image

2. menu also need to has 100vh 
image
3. you did not install full photos
image
 
image
4. and remove redundant margin-top 
 
image

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Hello!)

Good job!

Some improvements need to be applied: 
1) page shouldn't be reloaded after form submit

2) only an address should be as a link 
Screenshot 2023-02-28 at 20 29 56

3) card aren't the same height
Screenshot 2023-02-28 at 20 34 07

4)

**Review by etojeDenys — APPROVED** [review]
LGTM

**Pull request closed without merging**
