### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by victor-buldenko**
[DEMO LINK](https://victor-buldenko.github.io/Museum_2/).

### CODE REVIEW

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- better make indents between blocks with margins, it is better for navigation
- https://www.loom.com/share/a65646fb7d704c38a714f61d9c06a2e6
- this image shouldn't have an indent on the left
image

- These blocks should be on the same level
image

- The whole header should fit into the window
image

**Comment by victor-buldenko** [comment]
1. Where? What blocks you mean?
2. I don't understand loom message.
3. Ok
4. Ok
5. Ok

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
If you have questions, ask in fe_chat

1. I mean this. Better use margins, because it link to the top of the padding when you click the link in the menu
image

2. when I tap the logo in the menu, the cross icon stays on the nav bar instead of the menu icon

**Review by Bohdan-Maksymiuk — CHANGES_REQUESTED** [review]
Screenshot 2022-12-01 at 12 29 10

this is how design looks like (take a look over space between lines)

**Comment by Bohdan-Maksymiuk** [comment]
also check it in other places

**Review by AlisaVlasova — CHANGES_REQUESTED** [review]
1. make it 100vh 
image
2. if I click the orange btn in the menu close button on the banner doesn't change back
image

4. on the mobile menu and banner make the button fullwidth and check the address, header overlaps it a little

**Comment by victor-buldenko** [comment]
I dont, i push nothing. Its happend not first time.

**Pull request closed without merging**
