### PR TITLE
layout completed

### PR DESCRIPTION
**Pull request by willwildred**
[DESIGN FIGMA](https://www.figma.com/file/HL3XGt5ZatvJoYBhOaWY5x/museum-prototype?type=design&node-id=12431-2564&mode=design&t=7ShfZrN0gS6Khepg-0) 

[DEMO LINK](https://willwildred.github.io/Museum_2/)

### CODE REVIEW

**Review by vadiimvooo — CHANGES_REQUESTED** [review]
Good job. Here are a few fixes required:
1. It would be great to add some hover effect on burger button.
2. This block should be corrected according to design (gaps between links and address links, etc.)
3. All address fields should lead on google maps page.
4. Add transitions for all the interactive elements (buttons, links) to make the change smoothly.
5. Email in footer should be clickable. Use mailto param of href attribute for it.
6. Email input should have validation:
image
7. When subscribe button is clicked you should reset the input.
8.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
To improve:
1. Make this field are required before clicking on this button
image

2. Add the favicon on the page
image

3. Add the actual links for these social networks
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Almost done!
Need to change the autocomplete styles
image

**Review by vadiimvooo — APPROVED** [review]
Well done!)

**Pull request closed without merging**
