### PR TITLE
First Commit

### PR DESCRIPTION
**Pull request by rstarovoit**
[DEMO LINK](https://rstarovoit.github.io/Museum_2/)

### CODE REVIEW

**Review by OleksiiBlezniuk — CHANGES_REQUESTED** [review]
Your page shouldn't look like that on desktop
Screenshot 2022-09-07 at 12 52 27

Links `Календар подій`, `Усі новини`, `Почати` and `Архів виставок` should redirect to contacts or registration form instead of header

After form submit it redirect me to page with error, fix it

Distance between social medias links is too big on desktop. Also would be nice to add hover effects to them as well as for every link

Adress and phones should be links to map and to phone app as in previous landing

Add transition to buttons hover effects

Tablet and mobile layout is good 👍  But better to set 100vh height to header

**Comment by rstarovoit** [comment]
Thank you very much for your feedback! Tried to take into account all your comments. Hope this time will work better!)

I tried to set 100vh height to header as you recommended but it just cut the bottom of the header section with the date and line((

**Review by OleksiiBlezniuk — APPROVED** [review]
Good job! 
Better to change color on hover for menu links, `cause transition is not applied to underline and it looks bumpy

And don't forget about meaningful commit messages, shortly describe your changes, it's hard to understand what was done in commit from message `n-th commit`

**Comment by rstarovoit** [comment]
> Good job! Better to change color on hover for menu links, `cause transition is not applied to underline and it looks bumpy
> 
> And don't forget about meaningful commit messages, shortly describe your changes, it's hard to understand what was done in commit from message `n-th commit`

All done according to your comments! Many thanks for the advice!

**Pull request closed without merging**
