### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by TetianaBukhenko**
[DEMO LINK](https://TetianaBukhenko.github.io/Museum_2/).

### CODE REVIEW

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good work! Provide DEMO link to check your work

**Comment by TetianaBukhenko** [comment]
[DEMO LINK](https://TetianaBukhenko.github.io/Museum_2/).

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good! Some things to improve

1. It'll take a bit time, but really will be better :)
add max-width for element`s container, to not stretch it on huge screens, it looks weird )
image

2.add cursor pointer to ALL interactive elements(buttons etc)

3. menu should cover whole page
image


4. elements jumping on hover link, it shouldn't work so
image

5. control items are swapped on menu/main page
image


6. prevent default behavior on form submit and reset it after, remove blue bg on input autocomplete
image

7. links jumping too
image


8. use target _blank for this link
image

9. navigate to social
image

**Review by GUSILLUS — CHANGES_REQUESTED** [review]
Great job! But, always have some but)

1. Not the best hover effect for the burger button
image

2. Consider adding a simple animation for this underscore line
image

3. Consider adding the same hover effects for this link
image

4. Improve this hover it`s looks like not completed. Try to add transaction duration property to all hover effects it will improve them
image

5. If you don't have this functionality it is better to remove this component because it creates the question "Why dev don't fully implement it?"
image

6. Create some functionality for all these buttons. Maybe some alert with funny text or something else
image

7. Consider fixing Instagram icon
image

8. Make all these links workable. Also redesign all your navigation links so that they work within your one-page site
image

9. Taking into account that you will use this landing page in your portfolio, I would suggest improving this section, especially the style for the text on the right. You need to fill in the empty space with something
image

10. Add some hover effect for this card
image

11. I suggest making all such arrows round or at least rounded
image

12. Think of the landing page not as a queue of requests from the meta, but as a piece of your future, I'm sure it will be a great, portfolio) And think about how your landing page will look to a person who first came to it and whether they will have a question: why is it here if it doesn't work?

**Comment by TetianaBukhenko** [comment]
Sorry, I did not add better form validation, as I`ve just started the block about React. Once I learn how to do it with the help of the JS, I'll , definitely, add it to all landings.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
To improve:
1. Add a favicon on the page
image

2. Need to remove the scroll when this menu is open
image

**Comment by TetianaBukhenko** [comment]
I deleted the general scroll when the menu is opened, but when the menu is displayed on a tablet, there is a picture underneath and if the screen height is less than 1090 px the picture is cut inappropriately,  therefore, I added scroll, but only on tablets.

**Comment by GUSILLUS** [comment]
> I deleted the general scroll when the menu is opened, but when the menu is displayed on a tablet, there is a picture underneath and if the screen height is less than 1090 px the picture is cut inappropriately, therefore, I added scroll, but only on tablets.

It is better to ask any question in chat or Q&A because we don't have notifications here

Try to add `height: 100vh` and `overflow:hidden` to body when we open the menu on a tablet

**Review by GUSILLUS — CHANGES_REQUESTED** [review]
Amazing job! Just a little more)

If you don't understand any of my comments, please don't wait and contact us to talk to the mentors or come to a Q&A session. We will definitely figure it out)

1. Fix scroll on a tablet)

2. Better to write `This button in work` and you don`t need to navigate to a `#visit` section
image

3. Or hide the cursor on a disable button or add the same notification logic. And if you choose second don't forget about hover)
image
image
Like you did here
image


4. I like it, but can we make this picture bigger and start from the footer?
image

5. Amazing hover
image

6. Scroll issue in menu links
https://www.loom.com/share/78cd76a37eab4adab7216852d21eaff9

7. Z-Index problem
image

8. To fix it you just need to hide img tag and place it like bg image on a header_container div. Or my other advice
image

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. ` get rid of vertical scroll on tablet
2. button is not accessible 
image

**Review by VitaliyBondarenko1982 — APPROVED** [review]
Well done! Looks good to me.

**Pull request closed without merging**
