### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by SerjDSA**
[DEMO LINK](https://serjdsa.github.io/Museum_2/)

### CODE REVIEW

**Review by Esceype — CHANGES_REQUESTED** [review]
Wow, almost perfect.
But please fix the menu, at the moment for me it doesn`t work, nothing changes after click on the burger menu icon.

**Review by SerjDSA — COMMENTED** [review]
[DEMO LINK](https://serjdsa.github.io/Museum_2/)

**Review by SerjDSA — COMMENTED** [review]
[DEMO LINK](https://serjdsa.github.io/Museum_2/)

**Review by etojeDenys — CHANGES_REQUESTED** [review]
feel free to ask for some help in the chat about that menu

**Pull request closed without merging**
